CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `base_line_view` AS select `baseline_setting`.`rig_id` AS `rig_id`,`baseline_setting`.`valve_id` AS `valve_id`,`baseline_setting`.`response_time` AS `response_time`,`baseline_setting`.`Date_time` AS `date_time`,`baseline_setting`.`accum_pressure` AS `accum_pressure`,`baseline_setting`.`manif_pressure` AS `manif_pressure` from `baseline_setting` where `baseline_setting`.`sr_no` in (select max(`baseline_setting`.`sr_no`) from `baseline_setting` group by `baseline_setting`.`valve_id`,`baseline_setting`.`rig_id`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `base_line_data_view` AS select `base_line_view`.`rig_id` AS `rig_id`,`base_line_view`.`valve_id` AS `valve_id`,`base_line_view`.`response_time` AS `response_time`,`base_line_view`.`date_time` AS `date_time`,`base_line_view`.`accum_pressure` AS `accum_pressure`,`base_line_view`.`manif_pressure` AS `manif_pressure`,`resp_valve_master`.`valve_name` AS `valve_name` from (`resp_valve_master` left join `base_line_view` on(((`resp_valve_master`.`valve_id` = `base_line_view`.`valve_id`) and (`resp_valve_master`.`rig_id` = `base_line_view`.`rig_id`))));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `bop_stack_master_view` AS select `bop_stack_config`.`bop_stack_id` AS `bop_stack_id`,`bop_stack_config`.`bop_stack_name` AS `bop_stack_name` from `bop_stack_config` group by `bop_stack_config`.`bop_stack_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `f_month_colmn_log_view` AS select `function_tab`.`S_no` AS `S_no`,`function_tab`.`Rig_ID` AS `Rig_ID`,`function_tab`.`Valve_ID` AS `Valve_ID`,`function_tab`.`Valve_name` AS `Valve_name`,sum(`function_tab`.`Value`) AS `Valve_total`,`function_tab`.`Date_time` AS `Date_time`,dayofmonth(`function_tab`.`Date_time`) AS `com_day`,month(`function_tab`.`Date_time`) AS `com_month`,year(`function_tab`.`Date_time`) AS `com_year` from `function_tab` group by `function_tab`.`Rig_ID`,`function_tab`.`Valve_ID`,dayofmonth(`function_tab`.`Date_time`),month(`function_tab`.`Date_time`),year(`function_tab`.`Date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ff_month_colmn_log_view` AS select `function_fail`.`S_no` AS `S_no`,`function_fail`.`Rig_ID` AS `Rig_ID`,`function_fail`.`Valve_ID` AS `Valve_ID`,`function_fail`.`Valve_name` AS `Valve_name`,sum(`function_fail`.`Value`) AS `Valve_total`,`function_fail`.`Date_time` AS `Date_time`,dayofmonth(`function_fail`.`Date_time`) AS `com_day`,month(`function_fail`.`Date_time`) AS `com_month`,year(`function_fail`.`Date_time`) AS `com_year` from `function_fail` group by `function_fail`.`Rig_ID`,`function_fail`.`Valve_ID`,dayofmonth(`function_fail`.`Date_time`),month(`function_fail`.`Date_time`),year(`function_fail`.`Date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffmonth_close` AS select `rig_data`.`rig_id` AS `rig_id`,`rig_data`.`local_time` AS `close_date_time`,`rig_data`.`an_close_fail` AS `an_close_fail`,`rig_data`.`up_close_fail` AS `up_close_fail`,`rig_data`.`bl_close_fail` AS `bl_close_fail`,`rig_data`.`lo_close_fail` AS `lo_close_fail`,`rig_data`.`ch_close_fail` AS `ch_close_fail`,`rig_data`.`ki_close_fail` AS `ki_close_fail`,`rig_data`.`by_high_fail` AS `by_high_fail` from `rig_data`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffmonth_close_tot` AS select `ffmonth_close`.`rig_id` AS `rig_id`,`ffmonth_close`.`close_date_time` AS `close_date_time`,sum(`ffmonth_close`.`an_close_fail`) AS `an_close_fail`,sum(`ffmonth_close`.`up_close_fail`) AS `up_close_fail`,sum(`ffmonth_close`.`bl_close_fail`) AS `bl_close_fail`,sum(`ffmonth_close`.`lo_close_fail`) AS `lo_close_fail`,sum(`ffmonth_close`.`ch_close_fail`) AS `ch_close_fail`,sum(`ffmonth_close`.`ki_close_fail`) AS `ki_close_fail`,sum(`ffmonth_close`.`by_high_fail`) AS `by_high_fail`,month(`ffmonth_close`.`close_date_time`) AS `mnth`,year(`ffmonth_close`.`close_date_time`) AS `yr` from `ffmonth_close` group by `ffmonth_close`.`rig_id`,month(`ffmonth_close`.`close_date_time`),year(`ffmonth_close`.`close_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffmonth_open` AS select `rig_data`.`rig_id` AS `rig_id`,`rig_data`.`local_time` AS `open_date_time`,`rig_data`.`an_open_fail` AS `an_open_fail`,`rig_data`.`up_open_fail` AS `up_open_fail`,`rig_data`.`bl_open_fail` AS `bl_open_fail`,`rig_data`.`lo_open_fail` AS `lo_open_fail`,`rig_data`.`ch_open_fail` AS `ch_open_fail`,`rig_data`.`ki_open_fail` AS `ki_open_fail`,`rig_data`.`by_low_fail` AS `by_low_fail` from `rig_data`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffmonth_open_tot` AS select `ffmonth_open`.`rig_id` AS `rig_id`,`ffmonth_open`.`open_date_time` AS `open_date_time`,sum(`ffmonth_open`.`an_open_fail`) AS `an_open_fail`,sum(`ffmonth_open`.`up_open_fail`) AS `up_open_fail`,sum(`ffmonth_open`.`bl_open_fail`) AS `bl_open_fail`,sum(`ffmonth_open`.`lo_open_fail`) AS `lo_open_fail`,sum(`ffmonth_open`.`ch_open_fail`) AS `ch_open_fail`,sum(`ffmonth_open`.`ki_open_fail`) AS `ki_open_fail`,sum(`ffmonth_open`.`by_low_fail`) AS `by_low_fail`,month(`ffmonth_open`.`open_date_time`) AS `mnth`,year(`ffmonth_open`.`open_date_time`) AS `yr` from `ffmonth_open` group by `ffmonth_open`.`rig_id`,month(`ffmonth_open`.`open_date_time`),year(`ffmonth_open`.`open_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffunlog_close` AS select `function_fail`.`S_no` AS `S_no`,`function_fail`.`Rig_ID` AS `Rig_ID`,`function_fail`.`Valve_ID` AS `Valve_ID`,`function_fail`.`Valve_name` AS `Valve_name`,`function_fail`.`Value` AS `Value`,`function_fail`.`Date_time` AS `Date_time` from `function_fail` where ((`function_fail`.`Valve_ID` % 2) = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffunlog_open` AS select `function_fail`.`S_no` AS `S_no`,`function_fail`.`Rig_ID` AS `Rig_ID`,`function_fail`.`Valve_ID` AS `Valve_ID`,`function_fail`.`Valve_name` AS `Valve_name`,`function_fail`.`Value` AS `Value`,`function_fail`.`Date_time` AS `Date_time` from `function_fail` where ((`function_fail`.`Valve_ID` % 2) = 0);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffyear_close_tot` AS select `ffmonth_close`.`rig_id` AS `rig_id`,`ffmonth_close`.`close_date_time` AS `close_date_time`,sum(`ffmonth_close`.`an_close_fail`) AS `an_close_fail`,sum(`ffmonth_close`.`up_close_fail`) AS `up_close_fail`,sum(`ffmonth_close`.`bl_close_fail`) AS `bl_close_fail`,sum(`ffmonth_close`.`lo_close_fail`) AS `lo_close_fail`,sum(`ffmonth_close`.`ch_close_fail`) AS `ch_close_fail`,sum(`ffmonth_close`.`ki_close_fail`) AS `ki_close_fail`,sum(`ffmonth_close`.`by_high_fail`) AS `by_high_fail`,year(`ffmonth_close`.`close_date_time`) AS `yr` from `ffmonth_close` group by `ffmonth_close`.`rig_id`,year(`ffmonth_close`.`close_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ffyear_open_tot` AS select `ffmonth_open`.`rig_id` AS `rig_id`,`ffmonth_open`.`open_date_time` AS `open_date_time`,sum(`ffmonth_open`.`an_open_fail`) AS `an_open_fail`,sum(`ffmonth_open`.`up_open_fail`) AS `up_open_fail`,sum(`ffmonth_open`.`bl_open_fail`) AS `bl_open_fail`,sum(`ffmonth_open`.`lo_open_fail`) AS `lo_open_fail`,sum(`ffmonth_open`.`ch_open_fail`) AS `ch_open_fail`,sum(`ffmonth_open`.`ki_open_fail`) AS `ki_open_fail`,sum(`ffmonth_open`.`by_low_fail`) AS `by_low_fail`,year(`ffmonth_open`.`open_date_time`) AS `yr` from `ffmonth_open` group by `ffmonth_open`.`rig_id`,year(`ffmonth_open`.`open_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fmonth_close` AS select `rig_data`.`rig_id` AS `rig_id`,`rig_data`.`local_time` AS `close_date_time`,`rig_data`.`an_close` AS `an_close`,`rig_data`.`up_close` AS `up_close`,`rig_data`.`bl_close` AS `bl_close`,`rig_data`.`lo_close` AS `lo_close`,`rig_data`.`ch_close` AS `ch_close`,`rig_data`.`ki_close` AS `ki_close`,`rig_data`.`by_high` AS `by_high` from `rig_data`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fmonth_close_tot` AS select `fmonth_close`.`rig_id` AS `rig_id`,`fmonth_close`.`close_date_time` AS `close_date_time`,sum(`fmonth_close`.`an_close`) AS `an_close`,sum(`fmonth_close`.`up_close`) AS `up_close`,sum(`fmonth_close`.`bl_close`) AS `bl_close`,sum(`fmonth_close`.`lo_close`) AS `lo_close`,sum(`fmonth_close`.`ch_close`) AS `ch_close`,sum(`fmonth_close`.`ki_close`) AS `ki_close`,sum(`fmonth_close`.`by_high`) AS `by_high`,month(`fmonth_close`.`close_date_time`) AS `mnth`,year(`fmonth_close`.`close_date_time`) AS `yr` from `fmonth_close` group by `fmonth_close`.`rig_id`,month(`fmonth_close`.`close_date_time`),year(`fmonth_close`.`close_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fmonth_open` AS select `rig_data`.`rig_id` AS `rig_id`,`rig_data`.`local_time` AS `open_date_time`,`rig_data`.`an_open` AS `an_open`,`rig_data`.`up_open` AS `up_open`,`rig_data`.`bl_open` AS `bl_open`,`rig_data`.`lo_open` AS `lo_open`,`rig_data`.`ch_open` AS `ch_open`,`rig_data`.`ki_open` AS `ki_open`,`rig_data`.`by_low` AS `by_low` from `rig_data`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fmonth_open_tot` AS select `fmonth_open`.`rig_id` AS `rig_id`,`fmonth_open`.`open_date_time` AS `open_date_time`,sum(`fmonth_open`.`an_open`) AS `an_open`,sum(`fmonth_open`.`up_open`) AS `up_open`,sum(`fmonth_open`.`bl_open`) AS `bl_open`,sum(`fmonth_open`.`lo_open`) AS `lo_open`,sum(`fmonth_open`.`ch_open`) AS `ch_open`,sum(`fmonth_open`.`ki_open`) AS `ki_open`,sum(`fmonth_open`.`by_low`) AS `by_low`,month(`fmonth_open`.`open_date_time`) AS `mnth`,year(`fmonth_open`.`open_date_time`) AS `yr` from `fmonth_open` group by `fmonth_open`.`rig_id`,month(`fmonth_open`.`open_date_time`),year(`fmonth_open`.`open_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `funlog_close` AS select `function_tab`.`S_no` AS `S_no`,`function_tab`.`Rig_ID` AS `Rig_ID`,`function_tab`.`Valve_ID` AS `Valve_ID`,`function_tab`.`Valve_name` AS `Valve_name`,`function_tab`.`Value` AS `Value`,`function_tab`.`Date_time` AS `Date_time` from `function_tab` where ((`function_tab`.`Valve_ID` % 2) = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `funlog_open` AS select `function_tab`.`S_no` AS `S_no`,`function_tab`.`Rig_ID` AS `Rig_ID`,`function_tab`.`Valve_ID` AS `Valve_ID`,`function_tab`.`Valve_name` AS `Valve_name`,`function_tab`.`Value` AS `Value`,`function_tab`.`Date_time` AS `Date_time` from `function_tab` where ((`function_tab`.`Valve_ID` % 2) = 0);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fyear_close_tot` AS select `fmonth_close`.`rig_id` AS `rig_id`,`fmonth_close`.`close_date_time` AS `close_date_time`,sum(`fmonth_close`.`an_close`) AS `an_close`,sum(`fmonth_close`.`up_close`) AS `up_close`,sum(`fmonth_close`.`bl_close`) AS `bl_close`,sum(`fmonth_close`.`lo_close`) AS `lo_close`,sum(`fmonth_close`.`ch_close`) AS `ch_close`,sum(`fmonth_close`.`ki_close`) AS `ki_close`,sum(`fmonth_close`.`by_high`) AS `by_high`,year(`fmonth_close`.`close_date_time`) AS `yr` from `fmonth_close` group by `fmonth_close`.`rig_id`,year(`fmonth_close`.`close_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fyear_open_tot` AS select `fmonth_open`.`rig_id` AS `rig_id`,`fmonth_open`.`open_date_time` AS `open_date_time`,sum(`fmonth_open`.`an_open`) AS `an_open`,sum(`fmonth_open`.`up_open`) AS `up_open`,sum(`fmonth_open`.`bl_open`) AS `bl_open`,sum(`fmonth_open`.`lo_open`) AS `lo_open`,sum(`fmonth_open`.`ch_open`) AS `ch_open`,sum(`fmonth_open`.`ki_open`) AS `ki_open`,sum(`fmonth_open`.`by_low`) AS `by_low`,year(`fmonth_open`.`open_date_time`) AS `yr` from `fmonth_open` group by `fmonth_open`.`rig_id`,year(`fmonth_open`.`open_date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mnth_miss` AS select `miscellaneous_data`.`rig_id` AS `rig_id`,`miscellaneous_data`.`loss_id` AS `loss_id`,sum(`miscellaneous_data`.`loss_value`) AS `tot_loss_value`,month(`miscellaneous_data`.`date_time`) AS `mth`,year(`miscellaneous_data`.`date_time`) AS `yr` from `miscellaneous_data` group by `miscellaneous_data`.`rig_id`,`miscellaneous_data`.`loss_id`,`miscellaneous_data`.`loss_value`,month(`miscellaneous_data`.`date_time`),year(`miscellaneous_data`.`date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `month_colmn_log_view` AS select `rig_data`.`Id` AS `id`,`rig_data`.`rig_id` AS `rig_id`,`rig_data`.`local_time` AS `local_time`,dayofmonth(`rig_data`.`local_time`) AS `com_day`,month(`rig_data`.`local_time`) AS `com_month`,year(`rig_data`.`local_time`) AS `com_year`,sum(`rig_data`.`an_open`) AS `an_open_total`,sum(`rig_data`.`an_close`) AS `an_close_total`,sum(`rig_data`.`an_open_fail`) AS `an_open_fail_total`,sum(`rig_data`.`an_close_fail`) AS `an_close_fail_total`,sum(`rig_data`.`up_open`) AS `up_open_total`,sum(`rig_data`.`up_close`) AS `up_close_total`,sum(`rig_data`.`up_open_fail`) AS `up_open_fail_total`,sum(`rig_data`.`up_close_fail`) AS `up_close_fail_total`,sum(`rig_data`.`bl_open`) AS `bl_open_total`,sum(`rig_data`.`bl_close`) AS `bl_close_total`,sum(`rig_data`.`bl_open_fail`) AS `bl_open_fail_total`,sum(`rig_data`.`bl_close_fail`) AS `bl_close_fail_total`,sum(`rig_data`.`lo_open`) AS `lo_open_total`,sum(`rig_data`.`lo_close`) AS `lo_close_total`,sum(`rig_data`.`lo_open_fail`) AS `lo_open_fail_total`,sum(`rig_data`.`lo_close_fail`) AS `lo_close_fail_total`,sum(`rig_data`.`ch_open`) AS `ch_open_total`,sum(`rig_data`.`ch_close`) AS `ch_close_total`,sum(`rig_data`.`ch_open_fail`) AS `ch_open_fail_total`,sum(`rig_data`.`ch_close_fail`) AS `ch_close_fail_total`,sum(`rig_data`.`ki_open`) AS `ki_open_total`,sum(`rig_data`.`ki_close`) AS `ki_close_total`,sum(`rig_data`.`ki_open_fail`) AS `ki_open_fail_total`,sum(`rig_data`.`ki_close_fail`) AS `ki_close_fail_total`,sum(`rig_data`.`by_low`) AS `by_low_total`,sum(`rig_data`.`by_high`) AS `by_high_total`,sum(`rig_data`.`by_low_fail`) AS `by_low_fail_total`,sum(`rig_data`.`by_high_fail`) AS `by_high_fail_total`,sum(`rig_data`.`low_acc`) AS `low_acc_total`,sum(`rig_data`.`low_rig`) AS `low_rig_total`,sum(`rig_data`.`low_man`) AS `low_man_total`,sum(`rig_data`.`low_ann`) AS `low_ann_total`,sum(`rig_data`.`low_fluid`) AS `low_fluid_total`,sum(`rig_data`.`motor`) AS `motor_total` from `rig_data` group by `rig_data`.`rig_id`,dayofmonth(`rig_data`.`local_time`),month(`rig_data`.`local_time`),year(`rig_data`.`local_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ptrend_master_view` AS select `ptrend`.`press_id` AS `press_id`,`ptrend`.`press_name` AS `press_name` from `ptrend` group by `ptrend`.`press_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `response_time_data_view` AS select `res`.`sr_no` AS `sr_no`,`res`.`rig_id` AS `rig_id`,`res`.`valve_id` AS `valve_id`,`valv`.`valve_name` AS `valve_name`,`res`.`resp_time` AS `resp_time`,`res`.`resp_time_date` AS `resp_time_date`,`res`.`prev_resp_time` AS `prev_resp_time`,`res`.`prev_resp_time_date` AS `prev_resp_time_date`,`res`.`bs_line_resp_time` AS `bs_line_resp_time`,`res`.`bs_line_resp_time_date` AS `bs_line_resp_time_date` from (`response_time_data` `res` join `valve_2_master` `valv` on(((`res`.`rig_id` = `valv`.`rig_id`) and (`res`.`valve_id` = `valv`.`id`))));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `valve_hist_view1` AS select `valve_hist_data`.`Rig_id` AS `Rig_id`,`valve_hist_data`.`valve_id` AS `valve_id`,`valve_hist_data`.`value` AS `value`,`valve_hist_data`.`date_time` AS `date_time` from `valve_hist_data` where `valve_hist_data`.`S_no` in (select max(`valve_hist_data`.`S_no`) from `valve_hist_data` group by `valve_hist_data`.`valve_id`,`valve_hist_data`.`Rig_id`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `valve_hist_view2` AS select `valve_hist_data`.`Rig_id` AS `Rig_id`,`valve_hist_data`.`valve_id` AS `valve_id`,`valve_hist_data`.`value` AS `value`,`valve_hist_data`.`date_time` AS `date_time` from `valve_hist_data` where `valve_hist_data`.`S_no` in (select max(`valve_hist_data`.`S_no`) from `valve_hist_data` where (not(`valve_hist_data`.`S_no` in (select max(`valve_hist_data`.`S_no`) from `valve_hist_data` group by `valve_hist_data`.`valve_id`,`valve_hist_data`.`Rig_id`))) group by `valve_hist_data`.`valve_id`,`valve_hist_data`.`Rig_id`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `yr_miss` AS select `miscellaneous_data`.`rig_id` AS `rig_id`,`miscellaneous_data`.`loss_id` AS `loss_id`,sum(`miscellaneous_data`.`loss_value`) AS `tot_loss_value`,year(`miscellaneous_data`.`date_time`) AS `yr` from `miscellaneous_data` group by `miscellaneous_data`.`rig_id`,`miscellaneous_data`.`loss_id`,`miscellaneous_data`.`loss_value`,year(`miscellaneous_data`.`date_time`);

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `response_time_data_view_new` AS select `resp_valve_master`.`rig_id` AS `rig_id`,`resp_valve_master`.`valve_id` AS `valve_id`,`resp_valve_master`.`valve_name` AS `valve_name`,`valve_hist_view1`.`value` AS `resp_time`,`valve_hist_view1`.`date_time` AS `resp_time_date`,`valve_hist_view2`.`value` AS `prev_resp_time`,`valve_hist_view2`.`date_time` AS `prev_resp_time_date`,`base_line_view`.`response_time` AS `bs_line_resp_time`,`base_line_view`.`date_time` AS `bs_line_resp_time_date` from (((`resp_valve_master` left join `valve_hist_view2` on(((`resp_valve_master`.`rig_id` = `valve_hist_view2`.`Rig_id`) and (`resp_valve_master`.`valve_id` = `valve_hist_view2`.`valve_id`)))) left join `base_line_view` on(((`resp_valve_master`.`rig_id` = `base_line_view`.`rig_id`) and (`resp_valve_master`.`valve_id` = `base_line_view`.`valve_id`)))) left join `valve_hist_view1` on(((`resp_valve_master`.`rig_id` = `valve_hist_view1`.`Rig_id`) and (`resp_valve_master`.`valve_id` = `valve_hist_view1`.`valve_id`))));
